blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = 'blog'

urlpatterns = [path("", render_posts, name="posts"), path("<int:post_id>", post_detail, name="post_detail")]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from blog import urls

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="blog/images")
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to="portfolio/images")
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_posts(request):
    posts = Post.objects.all()
    return render(request,'posts.html',{'posts':posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post,pk=post_id)
    return render(request, 'post_detail.html', {"post": post})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request,'home.html', {'projects': projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}
{% block content %}
<h1>Blog</h1>
<h2>{{post.title}}</h2>
<h3>{{post.date}}</h3>

<div class="text-center">



    <div class="my-4">
        <p>{{post.description|safe}}</p>
    </div>
    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid"/>
</div>




{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}
{% block content %}

<h1>Blog</h1>

{% for post in posts %}


<div class="p-3">
    <div class="card card-body">
        <div class="row">
    
            <div class="col-3">
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid"/>
    
    
            </div>
    
            <div class="col-9">
                <h2>{{post.title}}</h2>
                <p>{{post.description|safe|truncatechars:100 }}</p>
                <p>{{post.date|date:'d M Y'|upper}}</p>
                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary btn-sm">Ver Mas</a>
    
            </div>
    
    
        </div>
    
    </div>

</div>

    
{% endfor %}
{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}

<header class="row">

<div  class= "col-md-4" >
    <img src="{% static 'portfolio/Fantasma_png.png' %}" alt="" width="200" height="150">  
</div>


<div class= "col-md-8 my-auto" >
    <h1><strong></strong>Tarea De Base De Datos</strong></h1>
    <p>Desafortunadamente, hubo publicidad. No siempre hay un feugiat para cada tirador pellentesco.
      Ahora es fácil de beber y el precio es fácil. Algunas pelotas de baloncesto están hechas para niños.
      Esta es la propaganda de la enfermedad. Hasta entonces, si no quieres beber, necesitas mucha proteína. 
      También el autor de la política inmobiliaria. 
      El Duis Porttitor debería ser la principal vía de financiación. 
      Hasta que no sea una caricatura, ni un gran objetivo.</p>
      <a class="btn btn-primary btn-lg rounded-0 my-3" href="{% static 'portfolio/ensayo.pdf' %}">Descarga</a>
</div>

</header>

<div class="row my-4 text-center">

    <h3>Mi Proyecto</h3>
    <P>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam, neque.
    </P>


{% for project in projects %}

<div class="col-md-4 p-4">
    <div class="card bg-light card-project">
        <img src="{{project.image.url}}" alt="{{project.title}} "class="card-img-top"/>

        <div class="card-body">
            <h2>{{project.title}}</h2> <p>{{project.description}}</p>
        
            {% if project.url %}
            <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{project.url}}</a>
            {% endif %}

        </div>

        </div>
    </div>
{% endfor %}
{% endblock %}
</div>



   

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
    {% include 'partials/navbar.html' %}
    
    "<div class="container p-4">
    {% block content %}

    {% endblock %}
    </div>

</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">Rafael Gonzalez</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ms-auto">
          <a class="nav-link active" aria-current="page" href="{% url 'blog:posts' %}">Blog</a>
          <li>
            <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/ensayo.pdf' %}"target= "_blank">Descarga</a>
          </li>
        </div>
      </div>
    </div>
  </nav>